version: '3.8'

services:
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:latest
    container_name: keycloak_prod
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: 35.200.191.112
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: dev-env
      KC_DB_PASSWORD: PqkAqV7LRWTgtx8KTNe
      KC_TRANSACTION_XA_ENABLED: "false"
      KC_HOSTNAME: keycloak.local
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - "8090:8080"
    networks:
      - keycloak_network
    command:
      - start
      - --spi-email-template-provider=freemarker-plus-mustache
      - --spi-email-template-freemarker-plus-mustache-enabled=true
      - --spi-theme-cache-themes=false

networks:
  keycloak_network:
