name: release version

on:
  push:
    branches:
      - main

env:
  # Version 24.0.4
  VERSION_MAJOR: 24
  VERSION_SUBMAJOR: 0
  VERSION_MINOR: 4

jobs:
  release-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
      - name: Build with Maven
        run: cd libs/ && mvn -U --batch-mode package && cd ../
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Version
        run: |
          TS=$(date +%s)
          echo "VERSION_MAJOR=$VERSION_MAJOR" >> $GITHUB_ENV
          echo "VERSION_SUBMAJOR=$VERSION_SUBMAJOR" >> $GITHUB_ENV
          echo "VERSION_MINOR=$VERSION_MINOR" >> $GITHUB_ENV
          echo "VERSION_TS=$TS" >> $GITHUB_ENV
          echo "VERSION_TAG=$VERSION_MAJOR.$VERSION_SUBMAJOR.$VERSION_MINOR.$TS" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            rajibsenrysadockerhub/phasetwo-containers:latest
            rajibsenrysadockerhub/phasetwo-containers:${{ env.VERSION_MAJOR }}
            rajibsenrysadockerhub/phasetwo-containers:${{ env.VERSION_MAJOR }}.${{ env.VERSION_SUBMAJOR }}
            rajibsenrysadockerhub/phasetwo-containers:${{ env.VERSION_MAJOR }}.${{ env.VERSION_SUBMAJOR }}.${{ env.VERSION_MINOR }}
            rajibsenrysadockerhub/phasetwo-containers:${{ env.VERSION_MAJOR }}.${{ env.VERSION_SUBMAJOR }}.${{ env.VERSION_MINOR }}.${{ env.VERSION_TS }}
      - name: Tag
        uses: cardinalby/git-tag-action@master
        env:
          TAG: v${{ env.VERSION_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # release-cluster:
  #   needs: release-public
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Version
  #       run: |
  #         TS=$(date +%s)
  #         echo "VERSION_MAJOR=$VERSION_MAJOR" >> $GITHUB_ENV
  #         echo "VERSION_SUBMAJOR=$VERSION_SUBMAJOR" >> $GITHUB_ENV
  #         echo "VERSION_MINOR=$VERSION_MINOR" >> $GITHUB_ENV
  #         echo "VERSION_TS=$TS" >> $GITHUB_ENV
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: "17"
  #         distribution: adopt
  #     - name: Set ssh keys
  #       uses: webfactory/ssh-agent@v0.7.0
  #       with:
  #         ssh-private-key: |
  #           ${{ secrets.IDP_WIZARD_SSH_KEY }}
  #     - name: Build with Maven
  #       run: cd cluster/ && cp ../conf/cache-ispn-jdbc-ping.xml . && cp ../conf/p2-entrypoint.sh . && cd ../
  #     - name: Remove ssh identities
  #       run: ssh-add -D
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         registry: docker.io
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Build and push to Docker Hub
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: "cluster/"
  #         file: "cluster/Dockerfile"
  #         platforms: linux/amd64,linux/arm64
  #         pull: true
  #         push: true
  #         tags: |
  #           rajibsenrysadockerhub/phasetwo-cluster:latest
  #           rajibsenrysadockerhub/phasetwo-cluster:${{ env.VERSION_MAJOR }}
  #           rajibsenrysadockerhub/phasetwo-cluster:${{ env.VERSION_MAJOR }}.${{ env.VERSION_SUBMAJOR }}
  #           rajibsenrysadockerhub/phasetwo-cluster:${{ env.VERSION_MAJOR }}.${{ env.VERSION_SUBMAJOR }}.${{ env.VERSION_MINOR }}
  #           rajibsenrysadockerhub/phasetwo-cluster:${{ env.VERSION_MAJOR }}.${{ env.VERSION_SUBMAJOR }}.${{ env.VERSION_MINOR }}.${{ env.VERSION_TS }}